mysql:
  host: localhost
  port: 3306
  database: plugins
  user: everything
  password: root

collector:
  sell-timeout: 20 # how long (in seconds) to wait for the data to be saved before discarding it
  item:
    material: BEACON
    name: '&c&lCollector'
    lore:
      - '&7Place this collector to automatically collect'
      - '&7all mob drops and crops in a chunk.'

guis:
  menu:
    name: '&cCollector - Menu'
    rows: 3
    items:
      contents:
        material: GRASS_BLOCK
        name: '&fContents'
        slot: 11
        action: CONTENTS
      settings:
        material: CLOCK
        name: '&fSettings'
        slot: 15
        action: SETTINGS
  contents:
    name: '&cCollector - Contents'
    variable-rows: true # if true, rows will be adjusted depending on amount of items
    rows: 5 # 45 slots in total
    item:
      lore:
        - '&7Amount: &f%amount%'
        - '&7Value: &f$%value%'
        - ''
        - '&7Left-click to sell item'
  settings:
    name: '&cCollector - Settings'
    rows: 3
    items:
      mode:
        slot: 11
        name: '&fCollector Mode'
        action: MODE
        whitelist:
          material: WHITE_WOOL
          lore:
            - '&7Mode: &fWhitelist'
            - ''
            - '&fWhitelist &7mode only allows materials'
            - '&7which are whitelisted. To edit the'
            - '&7whitelisted materials head to settings'
            - '&7and click on the &fEdit Blocks &7button.'
            - ''
            - '&7Left-click to switch to &fBlacklist &7mode'
        blacklist:
          material: BLACK_WOOL
          name: '&fCollector Mode'
          lore:
            - '&7Mode: &fBlacklist'
            - ''
            - '&fBlacklist &7mode allows all materials except'
            - '&7ones which are blacklisted. To edit the'
            - '&7blacklisted materials head to settings'
            - '&7and click on the &fEdit Blocks &7button.'
            - ''
            - '&7Left-click to switch to &fAll &7mode'
        all:
          material: GLASS
          name: '&fCollector Mode'
          lore:
            - '&7Mode: &fAll'
            - ''
            - '&fAll &7mode allows all materials to be'
            - '&7collected.'
            - ''
            - '&7Left-click to switch to &fWhitelist &7mode'
      editor:
        slot: 13
        material: STONE
        name: '&fEdit Blocks'
        action: BLOCK_EDIT

messages:
  no-permission: '&cYou do not have permission to use this command.'
  invalid-usage: '&cInvalid command usage: /collector <player> [amount].'
  invalid-player: '&cCould not find the player ''%player%''.'
  invalid-number: '&c%number% is not a valid number.'
  gave-collector: '&aSuccessfully gave &e%amount%x &acollector(s) to &e%player%&a.'
  received-collector: '&eYou &areceived &e%amount%x &acollector(s).'
  chunk-locked: '&cYou can''t modify collectors in this chunk at the moment.'
  collector-exists: '&cThere is already a collector in this chunk.'
  creation-fail: '&cAn issue occurred whilst trying to create a new collector.'
  placed-collector: '&aSuccessfully placed a collector at the chunk &ex: %x%&a, &ez: %z%&a.'
  deletion-fail: '&cAn issue occurred whilst trying to delete the collector.'
  destroyed-collector: '&aYou destroyed a collector, all the contents were sold.'
  collector-empty: '&cThere are no contents that can be sold in this collector.'
  contents-sold: '&aSuccessfully sold all the collector''s contents for &e$%total%&a.'
  material-sold: '&aSuccessfully sold &e%amount%x &aof &e%material% &afor &e$%total%&a.'
  cannot-sell-item: '&cYou cannot sell &e%item%&c.'
  removing-collector: '&aPlease wait whilst this collector is cleared from the database.'

drops:
  PIG:
    material: PORKCHOP
    range:
      min: 1
      max: 3
  COW:
    material: BEEF
    range:
      min: 1
      max: 3
  CHICKEN:
    material: CHICKEN
    range:
      min: 1
      max: 3
  SHEEP:
    material: MUTTON
    range:
      min: 1
      max: 3

prices:
  PORKCHOP: 10.0
  FEATHER: 2.5
  CHICKEN: 10.0
  BEEF: 10.0
  RABBIT_HIDE: 3.5
  WHITE_WHOOL: 8.0
  MUTTON: 10.0
  RABBIT: 10.0
  LEATHER: 3.5