{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.triumphteam",
    "module": "triumph-gui",
    "version": "3.1.3-COLLFIX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 72877,
          "sha512": "f0366e204120ec25e0d7feaa9b5b0ec913cd191620ccdf0a1c300b6e2c5b4f8dd48414be9fbd92f0e214d402e82989a589f3c354c04d653869bfbd396c63066b",
          "sha256": "041e1e09282b84796f26bb7f25de24a4e688b192fce98f90ef0a46af42efb914",
          "sha1": "72ee74b1377df6b3f385e309e5baf44c9b88bf30",
          "md5": "57d7b53675de4f13f44635492ac986a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 72877,
          "sha512": "f0366e204120ec25e0d7feaa9b5b0ec913cd191620ccdf0a1c300b6e2c5b4f8dd48414be9fbd92f0e214d402e82989a589f3c354c04d653869bfbd396c63066b",
          "sha256": "041e1e09282b84796f26bb7f25de24a4e688b192fce98f90ef0a46af42efb914",
          "sha1": "72ee74b1377df6b3f385e309e5baf44c9b88bf30",
          "md5": "57d7b53675de4f13f44635492ac986a3"
        }
      ]
    }
  ]
}
